### ISSUE TITLE
Does not compile with LDC 1.30.0 & VS Build Tools 2019

### ISSUE THREAD

**Issue by nxuv** [godot-dlang/godot-d#2]

**Comment by Superbelko** [comment]
Can you show error message?

**Comment by nxuv** [comment]
```
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException7__ClassZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException6__vtblZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException6__initZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
.dub\build\library-debug-windows-x86_64-ldc_v1.30.0-F48C6C820B5FF41BE10657ACA8512AD6\dlangtest.dll : fatal error LNK1120: 56 unresolved externals
Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe failed with status: 1120
ldc2 failed with exit code 1.
```
Plus a dozen error LNK2019 lines before ones I've copied here. So much that my terminal ran out of space

**Comment by Superbelko** [comment]
oh ok, have a look at demo project dub.json, it has linker flags for some reason, could be related to that.

`"dflags-windows-ldc": ["-link-defaultlib-shared=false"],`
